### PR TITLE
Api documentation update

### PR DESCRIPTION
**Pull request by klobermajer**
New sandbox feature - log in
image
image

Info about authorization
image

All api methods description updates. Added info about pagination (when needed), info about required parameters etc.

### CODE REVIEW

**Comment by mkurzeja** [comment]
@colejarczyk @divtjurczak I've checked Travis output and it seems there was an update in php-cs-fixer - all unit tests pass and the job fails on minor formatting issues. I suppose we should fix the master branch first, and then @klobermajer would merge the changes to this PR

**Comment by mkurzeja** [comment]
Sorry, I did not notice the issues are all connected to the newly added documentation. @klobermajer could you run php-cs-fixer?

**Comment by colejarczyk** [comment]
@mkurzeja @klobermajer can you fix failed Travis checks?

**Comment by mkurzeja** [comment]
The Travis fail is not related to any of our changes. If it does not fail for master branch, then I would assume that was a false negative

**Comment by colejarczyk** [comment]
@klobermajer @mkurzeja can you resolve conflict?

**Pull request merged**
